name: amazon
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax_flutter: ^1.0.0
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: Montserrat
      fonts:
       - asset: assets/fonts/Montserrat-Thin.ttf
         weight: 300
       - asset: assets\fonts\Montserrat-Light.ttf
         weight: 400
       - asset: assets\fonts\Montserrat-Medium.ttf
         weight: 600
       - asset: assets\fonts\Montserrat-SemiBold.ttf
         weight: 700
       - asset: assets\fonts\Montserrat-Bold.ttf
         weight: 800
         

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
